version: "3.8"


volumes:
  poseidon_db_volume:
  rabbitmq_data:


x-default-config: &default-config
    API_VERSION: "v1"
    APPLICATION_ENV: APPLICATION_ENV_VALUE
    APPLICATION_RELOAD: 0
    POSEIDON__MAIL_SERVER: "mailbe04.hoster.by"
    POSEIDON__MAIL_USERNAME: "no-reply@neroelectronics.com@mailbe04.hoster.by"
    POSEIDON__MAIL_PASSWORD: "zb4QRnkjNixUtSs"
    POSEIDON__MAIL_PORT: 2525
    POSEIDON__AMQP_BROKER__URI: "amqp://admin:admin@poseidon__broker__amqp:5672"
    POSEIDON__DB_URI: "postgresql://admin:admin@poseidon__db:5432/poseidon_db"
    POSEIDON__SYS_USER_ID: "6ff8eaba-b5b4-49b2-9a83-f48fcdf6d361"
    JWT_PUBLIC_KEY: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFvdSs5OGtoM3A2dURTZHZURW5ZVApyNVBSTHJzQ3JVRFRVWU1LanFPTGFTbnFWMmRuWjZLNDhERnhHWFJUcVoycXkyWmpTam5EdmJWazRUeWlhQTZkCjUwbTYvZzQ1OGxFN2ZxYjZtV0d6ajNpVW5HZm5yV2ZsT1VDQnhuMy9pYkRqbUExb21YbkFvdVV0QUtRQ0tvSTYKS2VGc2pvaWVSTzNVYVdNYnYwc0RheUtjOEFOUUFWOGFBY1Z6RTdtNjJYc2xUMHJ2TzBEQnByMHp0dFFXVkc0dApXYWZMbGhhdm43WFdxMzVpQWE5L1A0Rm45SUhOUkRMTHVGODc3SjN2c0NFOUxEdUxCS1Fkd0dZQ3ViNGpqRzVDCjR1RjlhTWoxa1pKSzAzWWVaVTVZZnBKSC9oOUV6MEFKRzI2ZTNMTWltQlBGT3NINUdjSXBFWGVFMCtXd3oxT1AKZVJzZXZ3Qzh4bWNPdEM2QkI1TkRNcS9nRmcvUitlVnpTYjBNUVJVRTgyYlJweTRhcmhwazllK3dBWDQ2TzgxNQpxa0VXQk8xSHJNajVpNmRIL2w2aDFONUVhZ0tLZXFBbU10YXorbDNxMzYwMThEY2V0dTNkZzV2Q3lBOGpRbVNFCm1TZ2tsL3pianV2QkNvS1k5Z0xBdzJRUDY3VDRCb0pOdUg3b25mL0RRa01yQTBuaCt6VWhROHdJNy9DemFDRWEKa0EvczVFemtLVFZqcXhTRXl2RGZqZUNlaHc2S01kbFl1YTVzS1Q5cXdrRDNxSnc3STZQK2hHd3padXNnQ1AvSQp0L1JDcTN5cG9LZjd1TWJ4WVJUU3ovaVhsaUh1a3VQRlh3T0Y5MTlBWWhSUFlRWlZjeG05WGVJOG9xYk92OG9sCm5sTGE5US9YWkxlSEtMWG05ZEU5VzJNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=='

services:
  poseidon__balancer:
    image: WERF_POSEIDON__BALANCER_DOCKER_IMAGE_NAME
    ports:
      - 6001:6001   # poseidon__db
      - 32727:32727 # poseidon__broker
      - 32726:32726 # poseidon__broker_ui
      - 32714:32714 # poseidon__api
      - 32756:32756 # poseidon__web
      - 8080:8080
    depends_on:
      - poseidon__api
      - poseidon__db
      - poseidon__broker__amqp
    command: [ nginx-debug, '-g', 'daemon off;' ]

  poseidon__db:
    image: library/postgres:13.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
      POSTGRES_DB: poseidon_db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    expose:
      - 5432
    volumes:
      - poseidon_db_volume:/var/lib/postgresql

  manager__poseidon__db:
    image: WERF_POSEIDON__COMMON_PYTHON_DOCKER_IMAGE_NAME
    environment:
      poseidon__SYS_USER_ID: "6ff8eaba-b5b4-49b2-9a83-f48fcdf6d361"
      poseidon__DB_URI: "postgresql://admin:admin@poseidon__db:5432/poseidon_db"
    depends_on:
      - poseidon__db
    command: "echo 'DO NOTHING'"

  poseidon__api:
    image: WERF_POSEIDON__COMMON_PYTHON_DOCKER_IMAGE_NAME
    restart: always
    environment:
      APPLICATION_PORT: 5500
      <<: *default-config
    command: "bash /docker_app/src/poseidon__api/bin-start.sh"
    expose:
      - 5500

  poseidon__web:
    image: WERF_POSEIDON__COMMON_PYTHON_DOCKER_IMAGE_NAME
    restart: always
    environment:
      APPLICATION_PORT: 5000
      INTERNAL_API_ENDPOINT: "http://poseidon_api:5500"
      <<: *default-config
    command: "/docker_app/src/poseidon__web/bin-start.sh"
    expose:
      - 5000

  poseidon__broker__amqp:
    image: rabbitmq:3.9.8-management
    expose:
      - 15672
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitm
    container_name: "poseidon__amqp"

  poseidon__email_worker:
    image: WERF_POSEIDON__COMMON_PYTHON_DOCKER_IMAGE_NAME
    restart: always
    environment:
      WORKER_NAME: "poseidon_input"
      <<: *default-config
    depends_on:
      - poseidon__broker__amqp
    command: "/docker_app/src/poseidon__uni_worker/bin-start.sh"
